### PR TITLE
Fix bugs discovered during MS review for final pre-publication release version

### PR DESCRIPTION
**Pull request by itcarroll**

### CODE REVIEW

**Comment by mbjones** [comment]
@itcarroll Awesome that you are updating the package.  I don't have cycles to review your changes, but maybe we could request @laurenmh or another of the package authors to review before you merge the PR?  And if not, then I'd say go ahead if all tests are passing and you've added good test coverage for new functionality. Sorry I can't jump in at the moment.  Let me know when you're ready to resubmit to CRAN.

**Comment by itcarroll** [comment]
Tests are passing, the bulk of commits here are refactoring of code and covered by existing tests.

**Comment by itcarroll** [comment]
@mbjones I uploaded source packages to win-builder for R-oldrelease, R-release, and R-devel. Results are emailed to the maintainer. Please fwd any failures. If none, could you update the CRAN comments to reflect success and submit? Thank you!

**Comment by mbjones** [comment]
There was a NOTE because the date in the description file is too old.  I
think it will pass once that is updated.  I tried to email the log emails,
but you sesync email didn’t forward, and I don’t seem to have another for
you.  You can check out the log file here:

https://win-builder.r-project.org/T2nuMEuL74N1/

Matt

**Pull request merged**
